# global scope is for values that are common to all component subcharts
global:
  # ingressClass will select the ingress provider
  ingressClass: "nginx"
  # clusterIssuer specifies the cluster-issuer installed on the target cluster
  clusterIssuer: "k8s-cluster-issuer"
  # image tag to use for armada components
  image:
    tag: "b292be39d6f960fcf20a8de26657ce79019abef5"
  # replica count  
  replicas: 1
  # cross-origin allowed origins
  corsAllowedOrigins:
    - "http://localhost:8082"
    - "http://localhost:8089"
  # armada API server url  
  armadaUrl: armadaserver.armada.svc.cluster.local:50051

binoculars:
  ingressHostNames: []
  
