# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

# Settings of specific linters
linters-settings:
  goimports:
    local-prefixes: github.com/armadaproject/armada-operator

# Settings for enabling and disabling linters
linters:
  disable-all: true
  enable:
    - goimports
    - govet

