project_name: armada-operator

version: 2

snapshot:
  version_template: "{{ .FullCommit }}"

dist: "dist"

builds:
  - env: [CGO_ENABLED=0]
    mod_timestamp: '{{ .CommitTimestamp }}'
    main: cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64

source:
  enabled: true
  name_template: '{{ replace .ProjectName "-" "_" }}_{{ replace .Version "-" "_" }}_source'
  format: "zip"

env:
  - GOPROXY={{ if index .Env "GOPROXY"  }}{{ .Env.GOPROXY }}{{ else }}https://proxy.golang.org,direct{{ end }}
  - GOSUMDB={{ if index .Env "GOSUMDB"  }}{{ .Env.GOSUMDB }}{{ else }}sum.golang.org{{ end }}
  - DOCKER_REPO={{ if index .Env "DOCKER_REPO"  }}{{ .Env.DOCKER_REPO }}/{{ else }}{{ end }}
  # GoReleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}

dockers:
  - id: operator
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.DOCKER_REPO }}armada-operator:latest"
      - "{{ .Env.DOCKER_REPO }}armada-operator:{{ .Version }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - --builder={{ .Env.DOCKER_BUILDX_BUILDER }}
      - --label=org.opencontainers.image.source=https://github.com/armadaproject/armada
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Exposes Armada resources as CRDs for a more Kubernetes-native experience
      - --label=org.opencontainers.image.url=https://github.com/armadaproject/armada-operator
      - --label=org.opencontainers.image.source=https://github.com/armadaproject/armada-operator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache

changelog:
  use:
    github
  sort: asc
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

release:
  disable: '{{ if index .Env "FULL_RELEASE" }}false{{ else }}true{{ end }}'
  mode: replace
  header: |
    ## Armada Operator v{{ .Version }}

    ### Docker images
    Armada Operator image is hosted on Dockerhub in the [{{ .Env.DOCKER_REPO }}](https://hub.docker.com/r/{{ .Env.DOCKER_REPO }}/armada-operator) organization.
    - `docker pull {{ .Env.DOCKER_REPO }}armada-operator:latest`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-operator:{{ .Version }}`

  footer: |
    **Full Changelog**: https://github.com/armadaproject/armada-operator/compare/{{ .PreviousTag }}...{{ .Tag }}

    * * *

    Have a new idea? Found a bug? Start a GitHub [Discussion](https://github.com/armadaproject/armada-operator/discussions) or [Issue](https://github.com/armadaproject/armada-operator/issues) and let's talk about it!

    Real-time interactions between Armada developers and users occurs primarily in CNCF Slack. To join us there:
    * If you already have an account on CNCF Slack, join #armada on https://cloud-native.slack.com
    * If you need an invitation to CNCF Slack, you can get one at https://slack.cncf.io
