apiVersion: install.armadaproject.io/v1alpha1
kind: ArmadaServer
metadata:
  name: armada-server
  namespace: armada
spec:
  pulsarInit: false
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-dev"
  hostNames: [server.demo.armadaproject.io]
  replicas: 1
  image:
    repository: gresearch/armada-server
    tag: 0.3.103
  applicationConfig:
    auth:
      anonymousAuth: true
      permissionGroupMapping:
        submit_jobs: ["everyone"]
        submit_any_jobs: ["everyone"]
        create_queue: ["everyone"]
        delete_queue: ["everyone"]
        cancel_jobs: ["everyone"]
        cancel_any_jobs: ["everyone"]
        reprioritize_jobs: ["everyone"]
        reprioritize_any_jobs: ["everyone"]
        watch_events: ["everyone"]
        watch_all_events: ["everyone"]
        execute_jobs: ["everyone"]
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
    redis:
      addrs:
        - redis-redis-ha.data.svc.cluster.local:6379
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Executor
metadata:
  name: armada-executor
  namespace: armada
spec:
  image:
    repository: gresearch/armada-executor
    tag: 0.3.103
  applicationConfig:
    apiConnection:
      armadaUrl: armada-server.armada.svc.cluster.local:50051
      forceNoTls: true
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Lookout
metadata:
  name: armada-lookout-v2
  namespace: armada
spec:
  replicas: 1
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-dev"
  hostNames: [lookoutv2.demo.armadaproject.io]
  image:
    repository: gresearch/armada-lookout-v2
    tag: 0.3.103
  prometheus:
    enabled: true
  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/lookoutv2/config.yaml
    # for the full list of configuration options.
    apiPort: 8080
    corsAllowedOrigins:
      - "https://ui.demo.armadaproject.io"
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookoutv2
        sslmode: disable
---
apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  name: armada-lookout-ingester-v2
  namespace: armada
spec:
  image:
    repository: gresearch/armada-lookout-ingester-v2
    tag: 0.3.103
  applicationConfig:
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookoutv2
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Scheduler
metadata:
  name: armada-scheduler
  namespace: armada
spec:
  replicas: 1
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-dev"
  hostNames: [scheduler.demo.armadaproject.io]
  image:
    repository: gresearch/armada-scheduler
    tag: 0.3.103
  applicationConfig:
    auth:
      anonymousAuth: true
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
---
apiVersion: install.armadaproject.io/v1alpha1
kind: SchedulerIngester
metadata:
  name: armada-scheduler-ingester
  namespace: armada
spec:
  replicas: 1
  image:
    repository: gresearch/armada-scheduler-ingester
    tag: 0.3.103
  applicationConfig:
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
---
apiVersion: install.armadaproject.io/v1alpha1
kind: EventIngester
metadata:
  name: armada-event-ingester
  namespace: armada
spec:
  replicas: 1
  image:
    repository: gresearch/armada-event-ingester
    tag: 0.3.103
  applicationConfig:
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
    redis:
      addrs:
        - redis-redis-ha.data.svc.cluster.local:6379
