queue: example
jobSetId: job-set-1
jobs:
  - namespace: default
    priority: 0
    podSpec:
      priorityClassName: armada-default
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: hello
          image: alpine:latest
          command:
            - sh
          args:
            - -c
            - echo "Hello Armada"
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 100m
