apiVersion: install.armadaproject.io/v1alpha1
kind: ArmadaServer
metadata:
  name: armada-server
  namespace: armada
spec:
  pulsarInit: false
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-dev"
  hostNames: []
  replicas: 1
  image:
    repository: gresearch/armada-server
    tag: 0.3.92
  applicationConfig:
    auth:
      anonymousAuth: true
      permissionGroupMapping:
        submit_jobs: ["everyone"]
        submit_any_jobs: ["everyone"]
        create_queue: ["everyone"]
        delete_queue: ["everyone"]
        cancel_jobs: ["everyone"]
        cancel_any_jobs: ["everyone"]
        reprioritize_jobs: ["everyone"]
        reprioritize_any_jobs: ["everyone"]
        watch_events: ["everyone"]
        watch_all_events: ["everyone"]
        execute_jobs: ["everyone"]
    postgres:
      connection:
        host: postgres-postgresql.data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
    redis:
      addrs:
        - redis-redis-ha.data.svc.cluster.local:6379
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Executor
metadata:
  name: armada-executor
  namespace: armada
spec:
  image:
    repository: gresearch/armada-executor
    tag: 0.3.92
  applicationConfig:
    apiConnection:
      armadaUrl: armada-server.armada.svc.cluster.local:50051
      forceNoTls: true
