kube-prometheus-stack:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  alertmanager:
    enabled: false

broker:
  replicaCount: 1

zookeeper:
  replicaCount: 1

bookkeeper:
  replicaCount: 1

proxy:
  replicaCount: 1
