{{ if eq .Values.clusterType "server" }}
apiVersion: install.armadaproject.io/v1alpha1
kind: EventIngester
metadata:
  name: {{ include "armada.fullname" . }}-eventingester
  namespace: {{ include "armada.fullname" . }}
  labels:
  {{- include "armada.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
    clusterType: {{ .Values.clusterType }}
  applicationConfig:
    redis:
      addrs: {{ .Values.redis.addrs }}
      password: {{ .Values.redis.password }}
      db: {{ .Values.redis.db }}
      poolSize: 1000
    pulsar:
      URL: {{ .Values.pulsar.url }}
      jobsetEventsTopic: {{ .Values.pulsar.eventsTopic }}
      receiveTimeout: 5s
      backoffTime: 1s
    subscriptionName: {{ .Values.pulsar.subscriptionName }}
    minMessageCompressionSize: 1024
    batchSize: 1048576  #1MB
    batchDuration: 500ms
    batchMessages: 10000
    eventRetentionPolicy:
      expiryEnabled: true
      retentionDuration: 336h
{{ end }}
