grpcPort: 50059
httpPort: 8080
metricsPort: 9000
grpc:
  keepaliveParams:
    maxConnectionIdle: 5m
    time: 2h
    timeout: 20s
  keepaliveEnforcementPolicy:
    minTime: 5m
    permitWithoutStream: false
uiConfig:
  armadaApiBaseUrl: {{ .Values.armadaUrl | default .Values.global.armadaUrl }}
  userAnnotationPrefix: "armadaproject.io/"
  binocularsEnabled: true
  binocularsBaseUrlPattern: {{ .Values.binocularsUrl | default .Values.global.binocularsUrl }}
  overviewAutoRefreshMs: 15000
  jobSetsAutoRefreshMs: 15000
  jobsAutoRefreshMs: 30000
  lookoutV2ApiBaseUrl: {{ .Values.lookoutV2Url | default .Values.global.lookoutV2Url }}
postgres:
  maxOpenConns: {{ .Values.postgres.maxOpenConns | default .Values.global.postgres.maxOpenConns }}
  maxIdleConns: {{ .Values.postgres.maxIdleConns | default .Values.global.postgres.maxIdleConns }}
  connMaxLifetime: {{ .Values.postgres.connMaxLifetime | default .Values.global.postgres.connMaxLifetime }}
  connection:
    host: {{ .Values.postgres.host | default .Values.global.postgres.host}}
    port: {{ .Values.postgres.port | default .Values.global.postgres.port }}
    user: {{ .Values.postgres.user | default .Values.global.postgres.user }}
    password: {{ .Values.postgres.password | default .Values.global.postgres.password }}
    dbname: {{ .Values.postgres.dbname }}
    sslmode: {{ .Values.postgres.sslmode | default .Values.global.postgres.sslmode }}
prunerConfig:
  daysToKeep: {{ .Values.prunerConfig.daysToKeep }}
  batchSize: {{ .Values.prunerConfig.batchSize }}
