apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "armada-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "armada-operator.fullname" . }}-serving-cert
  labels:
  {{- include "armada-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-armada-server
  failurePolicy: Fail
  name: armada-server.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - armada-servers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-binoculars
  failurePolicy: Fail
  name: mbinoculars.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - binoculars
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-eventingester
  failurePolicy: Fail
  name: meventingester.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eventingesters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-executor
  failurePolicy: Fail
  name: mexecutor.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - executors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-lookout
  failurePolicy: Fail
  name: mlookout.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lookout
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-lookoutingester
  failurePolicy: Fail
  name: mlookoutingester.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lookoutingesters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-scheduler
  failurePolicy: Fail
  name: mscheduler.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduler
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "armada-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-install-armadaproject-io-v1alpha1-scheduleringester
  failurePolicy: Fail
  name: mscheduleringester.kb.io
  rules:
  - apiGroups:
    - install.armadaproject.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduleringesters
  sideEffects: None