# Default values for armadaserver.
ingressHostNames: []
image:
  repository: gresearch/armada-server
  tag: 
replicas: 1
pulsarInit: false
postgres:
  dbname: postgres
  sslmode: false
pulsar:
  url: 
redis:
  db: 0  
