hostNames:
replicas: 2
image:
  repository: gresearch/armada-lookout
  tag: 
resources:
  limits:
    memory: 1Gi
    cpu: "0.5"
  requests:
    memory: 500Mi
    cpu: "0.3"
environment:
  LOG_FORMAT: json
prometheus:
  enabled: true
  labels:
    metrics: "true"
  prometheus: armada
  role: prometheus-rulefiles
postgres:
  dbname: lookout
prunerConfig:
  daysToKeep: 42
  batchSize: 1000
apiPort: 8080
