# permissions for end users to edit armadaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: armadaserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: armada-operator
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
  name: armadaserver-editor-role
rules:
- apiGroups:
  - install.armadaproject.io
  resources:
  - armadaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.armadaproject.io
  resources:
  - armadaservers/status
  verbs:
  - get
