# permissions for end users to edit binoculars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: binoculars-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: armada-operator
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
  name: binoculars-editor-role
rules:
- apiGroups:
  - install.armadaproject.io
  resources:
  - binoculars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.armadaproject.io
  resources:
  - binoculars/status
  verbs:
  - get
