# permissions for end users to view lookoutingesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lookoutingester-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: armada-operator
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
  name: lookoutingester-viewer-role
rules:
- apiGroups:
  - install.armadaproject.io
  resources:
  - lookoutingesters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.armadaproject.io
  resources:
  - lookoutingesters/status
  verbs:
  - get
