# permissions for end users to view eventingesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventingester-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: armada-operator
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventingester-viewer-role
rules:
- apiGroups:
  - install.armadaproject.io
  resources:
  - eventingesters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.armadaproject.io
  resources:
  - eventingesters/status
  verbs:
  - get
