kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Lookout UI
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  # Armada Server REST API
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # Armada Server gRPC API
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
- role: worker
