apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "armada.labels" . | nindent 4 }}
spec:
  image:
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag | default .Values.global.image.tag}}
  applicationConfig:
{{ tpl (.Files.Get "application-config.yaml") . | indent 4 }}
