---
apiVersion: install.armadaproject.io/v1alpha1
kind: Binoculars
metadata:
  name: binoculars-sample
  namespace: armada
spec:
  ingress:
    ingressClass: "nginx"
    labels: 
      hello: "world"
    annotations:
      hello: "world2"
  clusterIssuer: "k8s-cluster-issuer"
  hostNames: [localhost-binoculars]
  replicas: 2
  image:
    tag: 6141171b8bde8a03113090a819d728511c2dc39f
    repository: gresearch/armada-binoculars
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"

  environment:
  - name: LOG_FORMAT
    value: json

  prometheus:
    enabled: false
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles

  labels:
    armadaproject.io/app-id: "9670"

  applicationConfig:
    impersonateUsers: true
    corsAllowedOrigins:
      - "https://localhost"
    auth:
      anonymousAuth: true
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Executor
metadata:
  name: executor-sample
  namespace: armada
spec:
  image:
    repository: gresearch/armada-executor
    tag: 92fcbb6fd58753d2fcb67a9657aaccff95c3b069
  applicationConfig:
    apiConnection:
      armadaUrl: example.com:50051
      forceNoTls: true
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"
