apiVersion: install.armadaproject.io/v1alpha1
kind: ArmadaServer
metadata:
  labels:
    app.kubernetes.io/name: armadaserver
    app.kubernetes.io/instance: armadaserver-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: armadaserver-sample
  namespace: default
spec:
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "k8s-cluster-issuer"
  hostNames: [localhost]
  replicas: 1
  image:
    repository: gresearch/armada-server
    tag: f0102f1ba985a289e97e990b822d457a45a4ef73
  applicationConfig:
    server: example.com:443
    prometheusRule:
      kind: "prometheus"
    forceNoTls: true
    toleratedTaints:
      - key: armada.io/batch
        operator: in
---
apiVersion: install.armadaproject.io/v1alpha1
kind: EventIngester
metadata:
  labels:
    app.kubernetes.io/name: eventingester
    app.kubernetes.io/instance: eventingester-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: eventingester-sample
spec:
  image:
    repository: gresearchdev/armada-eventingester
    tag: v0.3.44
  applicationConfig:
    redis:
      addrs:
        - redis:6379
      password: ""
      db: 0
      poolSize: 1000
    pulsar:
      URL: pulsar://pulsar:6650
      jobsetEventsTopic: events
      receiveTimeout: 5s
      backoffTime: 1s
    subscriptionName: "events-ingester"
    minMessageCompressionSize: 1024
    batchSize: 1048576  #1MB
    batchDuration: 500ms
    batchMessages: 10000
    eventRetentionPolicy:
      expiryEnabled: true
      retentionDuration: 336h
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Lookout
metadata:
  labels:
    app.kubernetes.io/name: lookout
    app.kubernetes.io/instance: lookout-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: lookout-sample
  namespace: default
spec:
  migrateDatabase: true
  ingress:
    ingressClass: "nginx"
    labels:
      hello: "world"
    annotations:
      hello: "world2"
  clusterIssuer: "k8s-cluster-issuer"
  hostNames: [localhost]
  replicas: 2
  image:
    repository: gresearchdev/armada-lookout
    tag: v0.3.44
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"

  environment:
  - name: LOG_FORMAT
    value: json

  additionalVolumes:
    - name: testsecret
      secret:
        secretName: testsecret

  additionalVolumeMounts:
    - name: testsecret
      volume:
        name: testsecret
        mountPath: /etc/vimrc
        readOnly: true

  prometheus:
    enabled: true
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles

  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/lookout/config.yaml
    # for the full list of configuration options.
    grpcPort: 50059
    httpPort: 8080
    metricsPort: 9000
    postgres:
      connection:
        host: pghost
        port: 5432

