apiVersion: install.armadaproject.io/v1alpha1
kind: Scheduler
metadata:
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/instance: scheduler-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: scheduler-sample
  namespace: armada
spec:
  pruner:
    enabled: true
    schedule: "@hourly"
    resources:
      limits:
        memory: 1Gi
        cpu: 300m
    args:
      timeout: 5m
      batchsize: 1000
      expireAfter: 2h
  ingress:
    ingressClass: "nginx"
    labels:
      hello: "world"
    annotations:
      hello: "world2"
  clusterIssuer: "k8s-cluster-issuer"
  hostNames: [localhost]
  replicas: 2
  image:
    repository: gresearch/armada-scheduler
    tag: 0.5.0
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"

  environment:
  - name: LOG_FORMAT
    value: json

  prometheus:
    enabled: false
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles

  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/scheduler/config.yaml
    # for the full list of configuration options.
    cyclePeriod: 10s
    executorTimeout: 1h
    databaseFetchSize: 1000
    pulsarSendTimeout: 5s
    internedStringsCacheSize: 100000
    auth:
      anonymousAuth: true
    metrics:
      port: 9000
      refreshInterval: 30s
    pulsar:
      URL: "pulsar://pulsar-broker.armada.svc.cluster.local:6650"
      jobsetEventsTopic: "events"
      receiveTimeout: 5s
      backoffTime: 1s
    postgres:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: "30m"
      connection:
        host: postgresql.armada.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: scheduler
        sslmode: disable
    leader:
      mode: standalone
      leaseLockName: armada-scheduler
      LeaseLockNamespace: "" # This must be set so viper allows env vars to overwrite it
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      podName: "" # This must be set so viper allows env vars to overwrite it
    grpc:
      port: 50052
      keepaliveParams:
        maxConnectionIdle: 5m
        time: 120s
        timeout: 20s
      keepaliveEnforcementPolicy:
        minTime: 10s
        permitWithoutStream: true
    scheduling:
      executorTimeout: 10m
      nodeIdLabel: kubernetes.io/hostname
      preemption:
        enabled: true
        priorityClasses:
          armada-default:
            priority: 1000
            maximalResourceFractionPerQueue:
              memory: 0.99
              cpu: 0.99
          armada-preemptible:
            priority: 900
            maximalResourceFractionPerQueue:
              memory: 0.99
              cpu: 0.99
        defaultPriorityClass: armada-default
      queueLeaseBatchSize: 1000
      minimumResourceToSchedule:
        memory: 1000000 # 1Mb
        cpu: 0.1
      maximalResourceFractionToSchedulePerQueue:
        memory: 1.0
        cpu: 1.0
      maximalResourceFractionPerQueue:
        memory: 1.0
        cpu: 1.0
      maximalClusterFractionToSchedule:
        memory: 1.0
        cpu: 1.0
      maximumJobsToSchedule: 5000
      maxUnacknowledgedJobsPerExecutor: 2500
      maxQueueReportsToStore: 1000
      MaxJobReportsToStore: 10000
      defaultJobLimits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 8Gi
      defaultJobTolerations:
        - key: "armadaproject.io/armada"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      defaultJobTolerationsByPriorityClass:
        "":
          - key: "armadaproject.io/pc-armada-default"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        armada-default:
          - key: "armadaproject.io/pc-armada-default"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        armada-preemptible:
          - key: "armadaproject.io/pc-armada-preemptible"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      maxRetries: 5
      resourceScarcity:
        cpu: 1.0
      indexedResources:
        - cpu
        - memory
      gangIdAnnotation: armadaproject.io/gangId
      gangCardinalityAnnotation: armadaproject.io/gangCardinality
