apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  labels:
    app.kubernetes.io/name: lookoutingester
    app.kubernetes.io/instance: lookoutingester-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: lookoutingester-sample
spec:
  image:
    repository: gresearchdev/armada-lookout-ingester
    tag: v0.3.44
  applicationConfig:
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgres
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    metrics:
      port: 9000
    pulsar:
      enabled: true
      URL: "pulsar://pulsar:6650"
      jobsetEventsTopic: "events"
      receiveTimeout: 5s
      backoffTime: 1s
    paralellism: 1
    subscriptionName: "lookout-ingester"
    batchSize: 10000
    batchDuration: 500ms
    minJobSpecCompressionSize: 1024
    userAnnotationPrefix: "armadaproject.io/"
