apiVersion: install.armadaproject.io/v1alpha1
kind: Executor
metadata:
  labels:
    app.kubernetes.io/name: executor
    app.kubernetes.io/instance: executor-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: executor-sample
  namespace: default
spec:
  image:
    repository: gresearchdev/armada-executor
    tag: v0.3.44
  applicationConfig:
    apiConnection:
      armadaUrl: armada.demo.armadaproject.io:443
      forceNoTls: false
