apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  labels:
    app.kubernetes.io/name: lookoutingester
    app.kubernetes.io/instance: lookoutingester-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: lookoutingester-sample
spec:
  # TODO(user): Add fields here
