apiVersion: install.armadaproject.io/v1alpha1
kind: Lookout
metadata:
  labels:
    app.kubernetes.io/name: lookoutv2
    app.kubernetes.io/instance: lookoutv2-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: lookoutv2-sample
  namespace: armada
spec:
  ingress:
    ingressClass: "nginx"
    labels:
      hello: "world"
    annotations:
      hello: "world2"
  clusterIssuer: "k8s-cluster-issuer"
  hostNames: [localhost]
  replicas: 2
  image:
    repository: gresearch/armada-lookout-v2
    tag: 0.5.0
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"

  environment:
  - name: LOG_FORMAT
    value: json

  additionalVolumes:
    - name: testsecret
      secret:
        secretName: testsecret

  additionalVolumeMounts:
    - name: testsecret
      volume:
        name: testsecret
        mountPath: /etc/vimrc
        readOnly: true

  prometheus:
    enabled: true
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles

  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/lookoutv2/config.yaml
    # for the full list of configuration options.
    apiPort: 8080
    corsAllowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:8089"
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    prunerConfig:
      daysToKeep: 42
      batchSize: 1000
