apiVersion: install.armadaproject.io/v1alpha1
kind: SchedulerIngester
metadata:
  labels:
    app.kubernetes.io/name: scheduleringester
    app.kubernetes.io/instance: scheduleringester-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: scheduleringester-sample
  namespace: armada
spec:
  replicas: 1
  image:
    repository: gresearch/armada-scheduler-ingester
    tag: 0.5.0
  applicationConfig:
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: postgres
        sslmode: disable
    metrics:
      port: 9000
    pulsar:
      enabled: true
      URL: "pulsar://pulsar-broker.armada.svc.cluster.local:6650"
      jobsetEventsTopic: "events"
      receiveTimeout: 5s
      backoffTime: 1s
    paralellism: 1
    subscriptionName: "scheduler-ingester"
    batchSize: 10000
    batchDuration: 500ms
    minJobSpecCompressionSize: 1024
    userAnnotationPrefix: "armadaproject.io/"
