apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "armada-operator.fullname" . }}-serving-cert
  labels:
  {{- include "armada-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "{{ .Release.Namespace }}-operator.fullname" . }}-webhook-service.{{
    .Release.Namespace }}.svc'
  - '{{ include "{{ .Release.Namespace }}-operator.fullname" . }}-webhook-service.{{
    .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "armada-operator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert