grpcPort: 50059
httpPort: 8080
metricsPort: 9000
grpc:
  keepaliveParams:
    maxConnectionIdle: 5m
    time: 2h
    timeout: 20s
  keepaliveEnforcementPolicy:
    minTime: 5m
    permitWithoutStream: false
impersonateUsers: true
corsAllowedOrigins: {{ .Values.corsAllowedOrigins | default .Values.global.corsAllowedOrigins }}
auth:
  anonymousAuth: true
