# global scope is for values that are common to all component subcharts
global:
  # ingressClass will select the ingress provider
  ingressClass: "nginx"
  # clusterIssuer specifies the cluster-issuer installed on the target cluster
  clusterIssuer: "k8s-cluster-issuer"
  # postgres shared settings
  postgres:
    host: postgresql.armada.svc.cluster.local
    port: 5432
    user: postgres
    password: psw
    sslmode: disable
    maxOpenConns: 100
    maxIdleConns: 25
    connMaxLifetime: 30m
  # pulsar shared settings
  pulsar:
    url: pulsar://pulsar-broker.armada.svc.cluster.local:6650
  # redis shared settings
  redis:
    addrs: 
      - redis-master.armada.svc.cluster.local:6379
    db: 0
    poolSize: 1000
  # image tag to use for armada components
  image:
    tag: "70a27e91003a32b90cfb8d8bfd736c65556daae9"
  # replica count  
  replicas: 1
  # cross-origin allowed origins
  corsAllowedOrigins:
    - "http://localhost:8082"
    - "http://localhost:8089"
  # armada API server url  
  armadaUrl: armadaserver.armada.svc.cluster.local:50051
  
armadaserver:
  ingressHostNames: [server.armada.example.com]
  pulsarInit: true

binoculars:
  hostNames: [binoculars.armada.example.com]
    
lookout:
  hostNames: [lookout.armada.example.com]

lookout-v2:
  hostNames: [lookoutv2.armada.example.com]
  
scheduler:
  hostNames: [scheduler.armada.example.com]
