{{ if eq .Values.clusterType "server" }}
apiVersion: install.armadaproject.io/v1alpha1
kind: Lookout
metadata:
  name: lookout-sample
  namespace: armada
spec:
  hostNames: [lookout.armada.grlab.co.uk]
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-prod"
  replicas: 2
  image:
    repository: gresearch/armada-lookout
    tag: b292be39d6f960fcf20a8de26657ce79019abef5
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"
  environment:
  - name: LOG_FORMAT
    value: json
  prometheus:
    enabled: true
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles
  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/lookout/config.yaml
    # for the full list of configuration options.
    # See https://github.com/armadaproject/armada/blob/master/config/lookout/config.yaml
    # for the full list of configuration options.
    grpcPort: 50059
    httpPort: 8080
    metricsPort: 9000
    grpc:
      keepaliveParams:
        maxConnectionIdle: 5m
        time: 2h
        timeout: 20s
      keepaliveEnforcementPolicy:
        minTime: 5m
        permitWithoutStream: false
    uiConfig:
      armadaApiBaseUrl: "https://armada.grlab.co.uk"
      userAnnotationPrefix: "armadaproject.io/"
      binocularsEnabled: true
      binocularsBaseUrlPattern: "https://{CLUSTER_ID}.armada.grlab.co.uk/api"
      overviewAutoRefreshMs: 15000
      jobSetsAutoRefreshMs: 15000
      jobsAutoRefreshMs: 30000
      lookoutV2ApiBaseUrl: "https://lookoutv2.armada.grlab.co.uk"
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada-data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookout
        sslmode: disable
---
apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  namespace: armada
  name: lookoutingester-sample
spec:
  image:
    repository: gresearch/armada-lookout-ingester
    tag: b292be39d6f960fcf20a8de26657ce79019abef5
  applicationConfig:
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada-data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookout
        sslmode: disable
    metrics:
      port: 9000
    pulsar:
      enabled: true
      URL: "pulsar://pulsar-mini-broker.armada-data.svc.cluster.local:6650"
      jobsetEventsTopic: "events"
      receiveTimeout: 5s
      backoffTime: 1s
    paralellism: 1
    subscriptionName: "lookout-ingester"
    batchSize: 10000
    batchDuration: 500ms
    minJobSpecCompressionSize: 1024
    userAnnotationPrefix: "armadaproject.io/"
---
apiVersion: install.armadaproject.io/v1alpha1
kind: Lookout
metadata:
  name: lookoutv2-sample
  namespace: armada
spec:
  hostNames: [lookoutv2.armada.grlab.co.uk]
  ingress:
    ingressClass: "nginx"
  clusterIssuer: "letsencrypt-prod"
  replicas: 2
  image:
    repository: gresearch/armada-lookout-v2
    tag: b292be39d6f960fcf20a8de26657ce79019abef5
  resources:
    limits:
      memory: 1Gi
      cpu: "0.5"
    requests:
      memory: 500Mi
      cpu: "0.3"
  environment:
  - name: LOG_FORMAT
    value: json
  prometheus:
    enabled: true
    labels:
      metrics: "true"
      prometheus: armada
      role: prometheus-rulefiles
  applicationConfig:
    # See https://github.com/armadaproject/armada/blob/master/config/lookoutv2/config.yaml
    # for the full list of configuration options.
    apiPort: 8080
    corsAllowedOrigins:
      - "https://lookout.armada.grlab.co.uk"
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada-data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookoutv2
        sslmode: disable
    prunerConfig:
      daysToKeep: 42
      batchSize: 1000
---
apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  namespace: armada
  name: lookoutingesterv2-sample
spec:
  image:
    repository: gresearch/armada-lookout-ingester-v2
    tag: b292be39d6f960fcf20a8de26657ce79019abef5
  applicationConfig:
    postgres:
      maxOpenConns: 100
      maxIdleConns: 25
      connMaxLifetime: 30m
      connection:
        host: postgresql.armada-data.svc.cluster.local
        port: 5432
        user: postgres
        password: psw
        dbname: lookoutv2
        sslmode: disable
    metrics:
      port: 9000
    pulsar:
      enabled: true
      URL: "pulsar://pulsar-mini-broker.armada-data.svc.cluster.local:6650"
      jobsetEventsTopic: "events"
      receiveTimeout: 5s
      backoffTime: 1s
    paralellism: 1
    subscriptionName: "lookout-ingester-v2"
    batchSize: 10000
    batchDuration: 500ms
    minJobSpecCompressionSize: 1024
    userAnnotationPrefix: "armadaproject.io/"
{{ end }}      
