hostNames: [localhost]
replicas: 2
image:
  repository: gresearch/armada-lookout-v2
  tag: 
resources:
  limits:
    memory: 1Gi
    cpu: 500m
  requests:
    memory: 500Mi
    cpu: 300m
environment:
  LOG_FORMAT: json
prometheus:
  enabled: true
  scrapeInterval: "5m"
postgres:
  dbname: lookoutv2
prunerConfig:
  daysToKeep: 42
  batchSize: 1000
