name: "Setup Go"
description: "Setup Go with caching"
inputs:
  cache-prefix:
    description: "Prefix for the cache key"
    required: false
    default: "go"
  disable-cache:
    description: "Disable caching"
    required: false
    default: "false"
  go-version:
    description: "Version of Go. Default 1.21"
    required: false
    default: "1.22"
outputs:
  go-version:
    description: "The installed Go version"
    value: ${{ steps.setup-go.outputs.go-version }}
runs:
  using: "composite"
  steps:
    - id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
        cache: false
    - id: cache-info
      if: ${{ inputs.disable-cache != 'true' }}
      shell: bash
      run: echo path=$(go env GOCACHE) >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      if: ${{ inputs.disable-cache != 'true' }}
      with:
        path: ${{ steps.cache-info.outputs.path }}
        key: ${{ inputs.cache-prefix }}-go-${{ steps.setup-go.outputs.go-version }}-mod-${{ hashFiles('go.sum') }}
