name: Lint

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  go-lint:
    name: Golang Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: go-lint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "latest"
          only-new-issues: true
          args: "-c ./.golangci.yml --timeout=10m --issues-exit-code=1 --sort-results ./..."
