name: Lint

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  go-lint:
    name: Golang Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          skip-pkg-cache: true
          skip-build-cache: true
          args: "-c ./.golangci.yml --timeout=10m --issues-exit-code=1 --max-issues-per-linter=0 --sort-results ./..."
