name: Release Armada Operator - RC

on:
  workflow_run:
    types: [completed]
    workflows: [CI]
    branches:
      - main

permissions:
  contents: write

jobs:
  validate:
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'armadaproject'
    name: "Validate revision"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      # The given ref should belong to the main branch.
      # If it's main, it shouldn't be more than 2 commits away (in case another push happened in the meantime).
      # Anything else is invalid.
      - name: Validate ref
        run: |
          ref='${{ github.event.workflow_run.head_branch }}'
          sha='${{ github.event.workflow_run.head_sha }}'

          [ "$ref" == "main" ] &&
          [ $(git branch --contains=$sha main | wc -l) -eq 1 ] &&
          [ $(git rev-list --count $sha..main) -le 2 ]
          if [ $? -ne 0 ]; then
            echo "::error ::Invalid ref $ref $sha: must be a merge to main branch and not more than 2 commits away"
            exit 1
          fi
  release:
    name: Release
    needs: validate
    runs-on: "ubuntu-latest"
    environment: armada-dockerhub

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: go-build

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: "Docker login"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_PASS }}"

      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@v5"
        with:
          distribution: "goreleaser"
          version: v1.21.1
          args: "-f ./.goreleaser.yaml release --snapshot --skip-sbom --skip-sign --clean"
        env:
          DOCKER_REPO: "gresearch"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DOCKER_BUILDX_BUILDER: "${{ steps.buildx.outputs.name }}"

      - name: Run Docker push script
        run: ./scripts/docker-push.sh -t '${{ github.event.workflow_run.head_sha }}'
