name: Test

on:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  go-unit-tests:
    name: Golang Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"

      - name: make test
        run: make test

      - name: Go Test Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./operator.out # optional

  go-integration-tests:
    name: Golang Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"

      - name: make test-integration
        run: make test-integration
