name: Test

on:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  go-unit-tests:
    name: Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: go-unit-tests

      - name: Run unit tests
        run: make test-unit

      - name: Go Test Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./operator.out # optional

  go-integration-tests:
    name: Golang Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: go-integration-tests

      - name: Run integration tests
        run: make test-integration

  kind-e2e-tests:
    name: Kind e2e Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: kind-e2e-tests

      - name: Run kind e2e tests
        run: ./scripts/e2e-test.sh

  go-mod-up-to-date:
    name: Golang Mod Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: go-mod-up-to-date

      - name: Check for tidyness of go.mod and go.sum
        run: |
          go mod tidy

          changed=$(git status -s -uno | wc -l)

          echo -e "### Git status" >> $GITHUB_STEP_SUMMARY
          if [[ "$changed" -gt 0 ]]; then
            echo -e "Go modules are not synchronized. Please run 'go mod tidy' and commit the changes." >> $GITHUB_STEP_SUMMARY

            git status -s -uno >> $GITHUB_STEP_SUMMARY

            echo -e >> $GITHUB_STEP_SUMMARY
            echo -e "### Git diff" >> $GITHUB_STEP_SUMMARY

            echo -e '```' >> $GITHUB_STEP_SUMMARY
            git --no-pager diff >> $GITHUB_STEP_SUMMARY
            echo -e '```' >> $GITHUB_STEP_SUMMARY
          else
            echo -e "Go modules are synchronized." >> $GITHUB_STEP_SUMMARY
            echo -e >> $GITHUB_STEP_SUMMARY
          fi

          exit $changed

  manifests-up-to-date:
    name: Manifests Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          disable-cache: "true"

      - name: Check Kubernetes manifests
        run: |
          make manifests

          changed=$(git status -s -uno | wc -l)

          echo -e "### Git status" >> $GITHUB_STEP_SUMMARY
          if [[ "$changed" -gt 0 ]]; then
            echo -e "Kubernetes manifests are not synchronized. Please run 'make manifests' and commit the changes." >> $GITHUB_STEP_SUMMARY

            git status -s -uno >> $GITHUB_STEP_SUMMARY

            echo -e >> $GITHUB_STEP_SUMMARY
            echo -e "### Git diff" >> $GITHUB_STEP_SUMMARY

            echo -e '```' >> $GITHUB_STEP_SUMMARY
            git --no-pager diff >> $GITHUB_STEP_SUMMARY
            echo -e '```' >> $GITHUB_STEP_SUMMARY
          else
            echo -e "Kubernetes manifests are synchronized." >> $GITHUB_STEP_SUMMARY
            echo -e >> $GITHUB_STEP_SUMMARY
          fi

          exit $changed

  generated-code-up-to-date:
    name: Generated Code Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          disable-cache: "true"

      - name: Check generated code
        run: |
          make generate

          changed=$(git status -s -uno | wc -l)

          echo -e "### Git status" >> $GITHUB_STEP_SUMMARY
          if [[ "$changed" -gt 0 ]]; then
            echo -e "Generated code is not synchronized. Please run 'make generate' and commit the changes." >> $GITHUB_STEP_SUMMARY

            git status -s -uno >> $GITHUB_STEP_SUMMARY

            echo -e >> $GITHUB_STEP_SUMMARY
            echo -e "### Git diff" >> $GITHUB_STEP_SUMMARY

            echo -e '```' >> $GITHUB_STEP_SUMMARY
            git --no-pager diff >> $GITHUB_STEP_SUMMARY
            echo -e '```' >> $GITHUB_STEP_SUMMARY
          else
            echo -e "Generated code is synchronized." >> $GITHUB_STEP_SUMMARY
            echo -e >> $GITHUB_STEP_SUMMARY
          fi

          exit $changed

  helm-chart-up-to-date:
    name: Generated Helm Chart Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          disable-cache: "true"

      - name: Check generated Helm chart
        run: |
          make generate-helm-chart

          changed=$(git status -s -uno | wc -l)

          echo -e "### Git status" >> $GITHUB_STEP_SUMMARY
          if [[ "$changed" -gt 0 ]]; then
            echo -e "Generated Helm chart is not synchronized. Please run 'make generate-helm-chart' and commit the changes." >> $GITHUB_STEP_SUMMARY

            git status -s -uno >> $GITHUB_STEP_SUMMARY

            echo -e >> $GITHUB_STEP_SUMMARY
            echo -e "### Git diff" >> $GITHUB_STEP_SUMMARY

            echo -e '```' >> $GITHUB_STEP_SUMMARY
            git --no-pager diff >> $GITHUB_STEP_SUMMARY
            echo -e '```' >> $GITHUB_STEP_SUMMARY
          else
            echo -e "Generated Helm chart is synchronized." >> $GITHUB_STEP_SUMMARY
            echo -e >> $GITHUB_STEP_SUMMARY
          fi

          exit $changed

  crd-ref-docs-up-to-date:
    name: Generated CRD Reference Docs Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go-cache
        with:
          disable-cache: "true"

      - name: Check generated CRD reference docs
        run: |
          make generate-crd-ref-docs

          changed=$(git status -s -uno | wc -l)

          echo -e "### Git status" >> $GITHUB_STEP_SUMMARY
          if [[ "$changed" -gt 0 ]]; then
            echo -e "Generated CRD reference docs are not synchronized. Please run 'make generate-crd-ref-docs' and commit the changes." >> $GITHUB_STEP_SUMMARY

            git status -s -uno >> $GITHUB_STEP_SUMMARY

            echo -e >> $GITHUB_STEP_SUMMARY
            echo -e "### Git diff" >> $GITHUB_STEP_SUMMARY

            echo -e '```' >> $GITHUB_STEP_SUMMARY
            git --no-pager diff >> $GITHUB_STEP_SUMMARY
            echo -e '```' >> $GITHUB_STEP_SUMMARY
          else
            echo -e "Generated CRD reference docs is synchronized." >> $GITHUB_STEP_SUMMARY
            echo -e >> $GITHUB_STEP_SUMMARY
          fi

          exit $changed
