{{ if eq .Values.global.clusterType "server" }}
apiVersion: install.armadaproject.io/v1alpha1
kind: ArmadaServer
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Name }}
  labels:
  {{- include "armada.labels" . | nindent 4 }}
spec:
  pulsarInit: {{ .Values.pulsarInit }}
  ingress:
    ingressClass: {{ .Values.ingressClass }}
  clusterIssuer: {{ .Values.custerIssuer }}
  hostNames: {{ .Values.ingressHostNames }}
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
  applicationConfig:
{{ tpl (.Files.Get "applicationConfig.yaml") . | indent 4 }}
{{ end }}      
